CREATE TABLE IF NOT EXISTS wallets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    usd BIGINT NOT NULL DEFAULT 0,
    rub BIGINT NOT NULL DEFAULT 0,
    eur BIGINT NOT NULL DEFAULT 0,

    updated_at TIMESTAMP DEFAULT NOW()
);
